# Generated by Django 5.2.7 on 2025-11-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=13,
            ),
        ),
    ]
