# Generated by Django 5.2.7 on 2025-10-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price_new",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("USED", "Used"), ("LIKE_NEW", "Like New"), ("NEW", "New")],
                max_length=11,
                null=True,
            ),
        ),
    ]
