# Generated by Django 5.2.7 on 2025-11-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Price"),
                    ("HOURLY", "Hourly"),
                    ("UNIT", "Unit"),
                    ("PERSON", "Person"),
                    ("GROUP", "Group"),
                ],
                default="FIXED",
                max_length=10,
            ),
        ),
    ]
