# Generated by Django 5.2.7 on 2025-11-05 21:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listing_price_new_alter_listing_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="condition",
        ),
        migrations.CreateModel(
            name="Sublease",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.listing",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[("APARTMENT", "Apartment"), ("HOUSE", "House")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "number_of_bedrooms",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "number_of_roommates",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "distance_from_campus_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            bases=("core.listing",),
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={"verbose_name": "Listing", "verbose_name_plural": "Listings"},
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 1)), name="listing_price_min_1"
            ),
        ),
        migrations.CreateModel(
            name="PhysicalListing",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.listing",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("USED", "Used"),
                            ("LIKE_NEW", "Like New"),
                            ("NEW", "New"),
                        ],
                        max_length=11,
                    ),
                ),
            ],
            bases=("core.listing",),
        ),
        migrations.CreateModel(
            name="ItemListing",
            fields=[
                (
                    "physicallisting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.physicallisting",
                    ),
                ),
            ],
            bases=("core.physicallisting",),
        ),
        migrations.CreateModel(
            name="TextbookListing",
            fields=[
                (
                    "physicallisting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.physicallisting",
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
            ],
            bases=("core.physicallisting",),
        ),
    ]
