# Generated by Django 5.2.7 on 2025-11-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listing_price_new_alter_listing_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avg_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
