# Generated by Django 5.2.7 on 2025-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sublease",
            name="physical_address",
            field=models.CharField(default="", max_length=50),
        ),
    ]
