# Generated by Django 5.2.7 on 2025-11-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_description_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuplocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
