# Generated by Django 5.2.7 on 2025-11-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_listing_condition_sublease_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.listing",
                    ),
                ),
            ],
            bases=("core.listing",),
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price_new",
        ),
        migrations.AddField(
            model_name="physicallisting",
            name="price_new",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
