# Generated by Django 5.2.7 on 2025-11-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_report_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam"),
                    ("INNAPROPRIATE", "Innapropriate"),
                    ("HARASSEMENT", "Harassment"),
                    ("SCAM", "Scam"),
                    ("OTHER", "Other"),
                ],
                max_length=13,
            ),
        ),
    ]
