# Generated by Django 5.2.7 on 2025-11-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_service_remove_listing_price_new_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
