# Generated by Django 5.2.7 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_alter_report_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam"),
                    ("INNAPROPRIATE", "Innapropriate"),
                    ("HARASSMENT", "Harassment"),
                    ("SCAM", "Scam"),
                    ("OTHER", "Other"),
                ],
                max_length=13,
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("object_id", "reporter"), name="only-one-report"
            ),
        ),
    ]
